### ISSUE TITLE
Clarification of documentation?

### ISSUE THREAD

**Issue by Muzical84** [pismute/dashbars#1]
I'm not sure if I'm correctly understanding how to instantiate Dashbars in the browser?  (I picked this helper partially because it's been recently updated, so I'm HOPING someone sees this =-S  As opposed to when I asked if what Dashbars does is in HB, because I didn't know about this, at https://github.com/wycats/handlebars-site/issues/102)

``` javascript
    Dashbars.help(Handlebars);

    //template=Handlebars.compile($("#result-template").html(),{data:{level:Handlebars.logger.DEBUG}});

    template=Dashbars.compile($("#result-template").html(),{data:{level:Handlebars.logger.DEBUG}});

    result=template(convertedData);
```

But when I run it in Chrome, I get: "Uncaught TypeError: Cannot read property 'flatten' of undefined" on line 289 of the unminified file.  Most of this is JavaScript beyond my level, so...odds of me figuring this out myself are...not high...

This is doubly a problem since Dashbars does...something...on page load, before any of the above code is even invoked.

**Comment by pismute** [comment]
Hi. @Muzical84 

Dashbars depends on [lodash](https://lodash.com/) and [momentjs](http://momentjs.com/).

You must load them before using Dashbars. but If you do not use date(`d-xxx`) helpers, you can skip momentjs.

Thank you. I will improve documentation and code.

**Comment by Muzical84** [comment]
OK I apologize; I wasn't totally clear on that.  Thanks for replying quickly!  Is my syntax correct otherwise?  Also, does it matter in which order I include either of those in the head tag?

**Comment by pismute** [comment]
I made a sample for you. IMHO, it could help you.

http://codepen.io/pismute/pen/eNOOqe

**Comment by Muzical84** [comment]
Thanks!  ^_^
