### ISSUE TITLE
Please make this available via a CDN?

### ISSUE THREAD

**Issue by Muzical84** [pismute/dashbars#2]
For JSFiddle, CodePen.io , and even, for some folks' preferences, general use, some people prefer all of their libraries to be over a CDN vs. served locally.  [CDNJS](https://cdnjs.com/) seems to be designed for projects like this, (and it's actually the only place I CAN get a pre-minified copy of Handlebars, sadly,) so I was wondering if this project could be added to a CDN?  (Any is fine.) If I try and link to the GitHub copy directly, say I'm asking a question on StackOverflow and need to include this library, GitHub specifically "breaks" things in such a way that I cannot do that.

If it's too much trouble, I understand, but I would appreciate it.  I'm working on a tutorial for templating (basically hoping to save someone else the trouble of the past 2 weeks of my life) and right now I'm having to include the library manually.

**Comment by pismute** [comment]
Hi, I opened a PR(jsdelivr/jsdelivr#4511) for cdn. If it is accepted, I will beef up docs and close this issue to inform you.

It is very kind of you to do that.
